export const NAMING_CONSTANTS = {
  // Original: Greek Capital Lambda Λ (U+039B) - appears larger
  CHARACTER: "CHΛRΛCTER",
  MARKET: "MΛRKET",
  CHARACTER_ACCOUNT_DETECTIVE: "CHΛRΛCTER ΛCCOUNT ΔETECTIVE",
  GUILD: "GUILΔ",
  ITEM: "IT$M",
  MARKET_VOLUME_ALLOCATION: "MARKET VOLUME ΛLLOCATION",
};
