export const SEARCH_PLACEHOLDERS = [
  "Thunderfury, Blessed Blade of the Windseeker",
  "Ashbringer",
  "Sulfuras, Hand of Ragnaros",
  "Warglaive of Azzinoth",
  "Atiesh, Greatstaff of the Guardian",
  "Hammer of the Naaru",
  "Dragonwrath, Tarecgosa's Rest",
  "Fangs of the Father",
  "Gorehowl",
  "Shadowmourne",
  "Val'anyr, Hammer of Ancient Kings",
  "Thori'dal, the Stars' Fury",
  "Illidan Stormrage",
  "Arthas Menethil",
  "Jaina Proudmoore",
  "Thrall",
  "Anduin Wrynn",
  "Varian Wrynn",
  "Garrosh Hellscream",
  "Onyxia",
  "Nefarian",
  "Ragnaros",
  "Deathwing",
  "Al'Akir",
  "Kel'Thuzad",
  "The Lich King",
  "Yogg-Saron",
  "C'Thun",
  "N'Zoth",
  "Ensidia",
  "Nihilum",
  "Method",
  "Paragon",
  "Blood Legion",
  "Exorsus",
  "Limit",
  "Echo",
  "Pieces",
  "Fusion",
  "Frostmourne",
  "The Ashbringer",
  "Corrupted Ashbringer",
  "Hand of Edward the Odd",
  "Baron Rivendere",
  "Tirion Fordring",
  "Uther the Lightbringer",
  "Grommash Hellscream",
  "Cairne Bloodhoof",
  "Baine Bloodhoof",
  "Lor'themar Theron",
  "Nathanos Blightcaller",
  "Bolvar Fordragon",
  "Alexstrasza the Life-Binder",
  "Ysera the Dreamer",
  "Nozdormu the Timeless",
  "Malygos the Spell-Weaver",
  "Neltharion the Earth-Warder",
  "Kalecgos",
  "Chromie",
  "Wrathion",
  "Sabellian",
  "Sinestra",
  "Soridormi",
  "Tyrygosa",
  "Anveena Teague",
  "Krasus",
  "Rhonin",
  "Medivh",
  "Khadgar",
  "Aegwynn",
  "Nielas Aran",
  "Antonidas",
  "Kael'thas Sunstrider",
  "Lady Vashj",
  "Malfurion Stormrage",
  "Tyrande Whisperwind",
  "Maiev Shadowsong",
  "Shandris Feathermoon",
  "Jarod Shadowsong",
  "Cenarius",
  "Malorne",
  "Aviana",
  "Ursoc",
  "Ursol",
  "Agamaggan",
  "Goldrinn",
  "Tortolla",
  "Niuzao",
  "Xuen",
  "Chi-Ji",
  "Yu'lon",
  "Ordos",
  "Rukhmar",
  "Anzu",
  "Terokk",
  "Gul'dan",
  "Ner'zhul",
  "Blackhand",
  "Orgrim Doomhammer",
  "Durotan",
  "Draka",
  "Garad",
  "Geyah",
  "Drek'Thar",
  "Fenris Wolfbrother",
  "Kilrogg Deadeye",
  "Zul'jin",
  "Sen'jin",
  "Rastakhan",
  "Talanji",
  "Bwonsamdi",
  "Hakkar the Soulflayer",
  "Bloodlord Mandokir",
  "Jin'do the Hexxer",
  "High Priest Thekal",
  "High Priestess Arlokk",
  "High Priest Venoxis",
  "High Priestess Mar'li",
  "Gahz'ranka",
  "Gri'lek",
  "Hazza'rah",
  "Renataki",
  "Wushoolay",
  "Naxxramas",
  "Ahn'Qiraj",
  "Blackwing Lair",
  "Molten Core",
  "Karazhan",
  "Serpentshrine Cavern",
  "Tempest Keep",
  "Hyjal Summit",
  "Black Temple",
  "Sunwell Plateau",
  "Ulduar",
  "Trial of the Crusader",
  "Icecrown Citadel",
  "Ruby Sanctum",
  "Bastion of Twilight",
  "Blackwing Descent",
  "Throne of the Four Winds",
  "Firelands",
  "Dragon Soul",
  "Mogu'shan Vaults",
  "Heart of Fear",
  "Terrace of Endless Spring",
  "Throne of Thunder",
  "Siege of Orgrimmar",
  "Highmaul",
  "Blackrock Foundry",
  "Hellfire Citadel",
  "Emerald Nightmare",
  "Trial of Valor",
  "Nighthold",
  "Tomb of Sargeras",
  "Antorus, the Burning Throne",
  "Uldir",
  "Battle of Dazar'alor",
  "Crucible of Storms",
  "Eternal Palace",
  "Ny'alotha",
  "Castle Nathria",
  "Sanctum of Domination",
  "Sepulcher of the First Ones",
  "Vault of the Incarnates",
  "Aberrus",
  "Amirdrassil",
  "Nerub-ar Palace",
  "Liberation of Undermine",
  "Scarlet Monastery",
  "Stratholme",
  "Scholomance",
  "Blackrock Depths",
  "Blackrock Spire",
  "Dire Maul",
  "Maraudon",
  "Zul'Farrak",
  "Sunken Temple",
  "Razorfen Downs",
  "Razorfen Kraul",
  "Uldaman",
  "Gnomeregan",
  "The Deadmines",
  "Shadowfang Keep",
  "Wailing Caverns",
  "Ragefire Chasm",
  "Stockades",
  "Stormwind Stockade",
  "Scarlet Halls",
  "Gate of the Setting Sun",
  "Shado-Pan Monastery",
  "Siege of Niuzao Temple",
  "Mogu'shan Palace",
  "Temple of the Jade Serpent",
  "Stormstout Brewery",
  "Grim Batol",
  "The Vortex Pinnacle",
  "Lost City of the Tol'vir",
  "Halls of Origination",
  "End Time",
  "Well of Eternity",
  "Hour of Twilight",
  "Zul'Aman",
  "гнев-анархии@ревущий-фьорд",
  "инициатива@gordunni",
  "блюрателла@gordunni",
  "рак-гейминг@свежеватель-душ",
  "депортация@gordunni",
  "форжспирит@gordunni",
  "сакросантус@gordunni",
  "рейннон@gordunni",
  "sasukegodx@twisting-nether",
  "вандерплз@gordunni",
  "йондадх@gordunni",
  "докторйозя@gordunni",
  "акулов@howling-fjord",
  "редизтрибут@howling-fjord",
];

export function formatSearchPlaceholder(name: string): string {
  return `cmnw search "${name}"`;
}
