version: '3.8'

services:
  commonwealth:
    image: ghcr.io/alexzedim/commonwealth:latest
    container_name: commonwealth
    restart: always
    command: [ 'node','dist/apps/conglomerat/main.js' ]
    ports:
      - '5000:8000'
    environment:
      - NODE_ENV=${NODE_ENV}

  cmnw:
    image: ghcr.io/alexzedim/cmnw:latest
    container_name: cmnw
    restart: always
    command: [ 'npm','start' ]
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
