version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      nginx_net:
    volumes:
      - ./nginx/cmnw.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    networks:
      nginx_net:
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  commonwealth:
    image: ghcr.io/alexzedim/commonwealth:latest
    container_name: commonwealth
    restart: always
    command: [ 'node','dist/apps/conglomerat/main.js' ]
    ports:
      - '5000:8000'
    environment:
      - NODE_ENV=${NODE_ENV}

  cmnw:
    image: ghcr.io/alexzedim/cmnw:latest
    container_name: cmnw
    restart: always
    command: [ 'npm','start' ]
    ports:
      - '3000:8000'
    environment:
      - NODE_ENV=${NODE_ENV}
