import { Faction } from '../enums';
import { characterMount } from './characterMount';
import { characterPet } from './characterPet';
import { characterProfession } from './characterProfession';
import { characterRaidProgress } from './characterRaidProgress';

export type characterResponse = {
  _id: string,
  realm: string,
  name: string,
  realm_id: number,
  id: number,
  realm_name: string,
  guild: string,
  guild_id: string,
  guild_guid: number,
  guild_rank: number,
  hash_a: string,
  hash_b: string,
  hash_f: string,
  hash_t: string,
  race: string,
  character_class: string,
  active_spec: string,
  gender: string,
  faction: Faction,
  level: number,
  achievement_points: number,
  status_code: number,
  average_item_level: number,
  equipped_item_level: number,
  chosen_covenant: string,
  renown_level: number,
  last_modified: Date,
  created_by: string,
  updated_by: string,
  avatar: string,
  inset: string,
  main: string,
  personality: string,
  mounts: [characterMount],
  pets: [characterPet],
  professions: [characterProfession],
  raid_progress: [characterRaidProgress],
  looking_for_guild: string,
  rio_score: number,
  wcl_percentile: number,
  battle_tag: string,
  days_from: number,
  days_to: number,
  role: string,
  transfer: boolean,
  languages: string[],
  updatedAt: Date,
  createdAt: Date,
}
